projects:
  MyAppSyncAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: l5gya3xc3vczdmvzg3caaqlo24
        maxDepth: 2
extensions:
  amplify:
    version: 3
