/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.



const config = {
  API: {
    GraphQL: {
      endpoint: 'https://gitdh2dngnemje3mpntyycikae.appsync-api.eu-central-1.amazonaws.com/graphql',
      region: 'eu-central-1',
      defaultAuthMode: 'iam',
    },
  },
};

export default config;
